appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Gs7LLX7qD0cb1si8X5BEmpybsCqNnEzvDt+W8pJjCmtLhk263nqetvasrKB1On9ZL2v6+ExF+Dd6uFUqzkaQlLNPz3fjFb0IVdUNWBmoFBP8UPJ2KR+V8h8lT91kIzd1bw9OfAYyUdyjFOnfzZkHN56ppdmFSHPrRy+XNAuMyNjJGztbXoqKuTBePsyzkbxXvpQ7qSE7dNBloRiU4XBe6my6yYATT5VEYoEGyR4J3ZTkuXC3H2se8oU/HponQDKJSZ+FCnae4EVgrq2F6b8ILbnz+zGAOXf577QR2Wf7bV+kJQNSwhtl8AtY3NuFm0xsztnxSlNGyqIip+wtbMaEwkAA34Tb2XQd/uAo2B0j1a4DOi11NdeL5x3h36hHf2mZ98oSm2zZyiovNlH7EbYs8FL8GVZ9J2g/Kxzr2zIE5gBYxrDdZgxeXZ6N+XNRQ6IrrntE2ftITPYquysywJkVNtCk4o/8UCsogZtu88mYu+BqbG6Bsry0QPNpLnnQiN0U81J34dBtRwDP+RKZmJapf/rhok0LOxt21j8Nvr0uxk5vRwh5PWx40384p1CkyUjRVAxndVONPEkW5K61XJah4CMcbe4jy36G2va91QYB3eatGdAiOsfdOwv9SFp942p1zCwDKmpmc1UVfTY/AF+AAQnanPR4U9GXT81cETLZfp0=}
provider:
  win: azure
conda_forge_output_validation: true
